Repository bounswe/bounswe2024group8, pull requests merged in 2024-12, with the labels that each got.

#400 model render camera fix
  3Design/frontend/src/components/DViewer/DViewer.tsx
Labels: Type: Enhancement, Priority: Low, Duration: Short, Status: Completed

#413 Lab8 mobile
  3Design/mobile/App.js
  3Design/mobile/app/screens/SearchScreen.js
  3Design/mobile/package-lock.json
Labels: Type: Enhancement, Priority: High, Status: Review Needed

#402 Lab8
  3Design/frontend/src/components/DViewer/DViewer.tsx
  3Design/mobile/App.js
  3Design/mobile/app/screens/FeedScreen.js
  3Design/mobile/app/screens/SearchScreen.js
  3Design/mobile/package-lock.json
Labels: Documentation, Type: Enhancement, Priority: High, Duration: Short, Status: Completed

#414 Implement user search and get user response endpoints.
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/controller/UserController.java
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/payload/UserResponse.java
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/repository/UserRepository.java
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/service/UserService.java
Labels: Type: Enhancement

#418 Create 6 new achievements
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/model/enums/Achievement.java
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/repository/AnnotationRepository.java
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/repository/FollowingRepository.java
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/repository/PostRepository.java
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/repository/ReactionRepository.java
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/service/AchievementService.java
Labels: Type: Enhancement

#425 Fix like and dislike buttons for posts and comments in mobile application
  3Design/mobile/app/components/Post.js
  3Design/mobile/app/screens/FeedScreen.js
  3Design/mobile/app/screens/PostScreen.js
Labels: Type: Bug, Priority: Medium, Status: Review Needed, Duration: Mid

#428 3design frontend user search results
  3Design/frontend/src/components/SearchResults/SearchResults.tsx
  3Design/frontend/src/components/SearchResults/UserDisplayer/UserDisplayer.module.css
  3Design/frontend/src/components/SearchResults/UserDisplayer/UserDisplayer.tsx
Labels: Type: Enhancement, Priority: Medium, Duration: Short, Status: Completed

#431 Added achievements feature to the profile screen
  3Design/mobile/app/navigation/TabNavigator.js
  3Design/mobile/app/screens/ProfileScreen.js
  3Design/mobile/package-lock.json
  3Design/mobile/package.json
Labels: Type: Enhancement, Priority: Medium, Status: Review Needed, Duration: Mid

#432 3design frontend profile page improvement
  3Design/frontend/src/components/PageHeader/PageHeader.tsx
  3Design/frontend/src/components/ProfilePage/ProfilePage.module.css
  3Design/frontend/src/components/ProfilePage/ProfilePage.tsx
Labels: Priority: High, Duration: Short, Status: In Progress

#435 Create post dialog form implemented
  3Design/frontend/.gitignore
  3Design/frontend/src/components/CreatePost/CreatePost.tsx
  3Design/frontend/src/components/GalleryPost/Clickable/GalleryPost.tsx
  3Design/frontend/src/components/GalleryPost/Page/GalleryPost.tsx
  3Design/frontend/src/components/interfaces.ts
  3Design/frontend/src/components/tsfunctions.ts
  3Design/frontend/src/resources/json-files/DesignProperties.json
Labels: Type: Enhancement, Duration: Mid

#437 Feed paginated. Style fixes.
  3Design/frontend/src/components/CreatePost/ChallengePost.tsx
  3Design/frontend/src/components/CreatePost/CreatePost.tsx
  3Design/frontend/src/components/DiscussionPost/DiscussionPost.module.css
  3Design/frontend/src/components/DiscussionPost/Page/DiscussionPost.tsx
  3Design/frontend/src/components/Feed/Feed.tsx
  3Design/frontend/src/components/GalleryPost/GalleryPost.module.css
  3Design/frontend/src/components/GalleryPost/Page/GalleryPost.tsx
  3Design/frontend/src/components/GenericFeed/GenericFeed.tsx
  3Design/frontend/src/components/HomePage/HomePage.tsx
  3Design/frontend/src/components/PostPage/PostPage.module.css
Labels: Type: Enhancement

#433 Swagger descriptions for post,user,tournament,category controller
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/controller/CategoryController.java
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/controller/PostController.java
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/controller/TournamentController.java
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/controller/UserController.java
Labels: Documentation, Priority: Medium, Status: Review Needed, Duration: Mid

#441 Implement post update and delete features.
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/controller/PostController.java
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/payload/PostUpdateRequest.java
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/repository/AnnotationRepository.java
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/repository/CommentRepository.java
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/repository/ReactionRepository.java
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/repository/TournamentEntryRepository.java
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/service/CommentService.java
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/service/PostService.java
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/service/TournamentService.java
Labels: Type: Enhancement, Priority: High, Duration: Long

#446 Implement post search with tags
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/controller/PostController.java
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/repository/PostRepository.java
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/service/PostService.java
Labels: Type: Enhancement

#448 3design frontend annotations improvement
  3Design/frontend/src/components/DiscussionPost/DiscussionPost.module.css
  3Design/frontend/src/components/DiscussionPost/Page/DiscussionPost.tsx
  3Design/frontend/src/components/GalleryPost/GalleryPost.module.css
  3Design/frontend/src/components/GalleryPost/Page/GalleryPost.tsx
Labels: Priority: High, Duration: Short, Status: In Progress

#455 3design mobile
  3Design/mobile/app/components/Post.js
  3Design/mobile/app/screens/CreatePostScreen.js
  3Design/mobile/app/screens/PostScreen.js
  3Design/mobile/app/screens/SearchScreen.js
Labels: Status: Completed

#457 3design mobile
  3Design/mobile/app/navigation/StackNavigator.js
  3Design/mobile/app/screens/LeaderboardScreen.js
  3Design/mobile/app/screens/ProfileScreen.js
Labels: Status: Completed
