Repository bounswe/bounswe2024group8, pull requests merged in 2024-11, with the labels that each got.

#268 Generic feed implemented, categories initiated
  3Design/frontend/src/components/Feed/Feed.tsx
  3Design/frontend/src/components/GenericFeed/GenericFeed.module.css
  3Design/frontend/src/components/GenericFeed/GenericFeed.tsx
  3Design/frontend/src/components/HomePage/HomePage.tsx
  3Design/frontend/src/components/PageHeader/PageHeader.module.css
  3Design/frontend/src/components/PageHeader/PageHeader.tsx
  3Design/frontend/src/components/SideBar/SideBar.module.css
  3Design/frontend/src/components/SideBar/SideBar.tsx
  3Design/frontend/src/components/tsfunctions.ts
  3Design/frontend/src/resources/json-files/Categories.json
  3Design/frontend/src/resources/json-files/MockGenericPosts.json
Labels: Duration: Short

#285 3design frontend
  3Design/frontend/src/components/DiscussionPost/DiscussionPost.module.css
  3Design/frontend/src/components/DiscussionPost/DiscussionPost.tsx
  3Design/frontend/src/components/GalleryPost/GalleryPost.module.css
  3Design/frontend/src/components/GalleryPost/GalleryPost.tsx
  3Design/frontend/src/components/GenericFeed/GenericFeed.tsx
  3Design/frontend/src/components/tsfunctions.ts
Labels: Duration: Short

#281 Feature/category
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/controller/CategoryController.java
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/repository/CategoryRepository.java
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/service/CategoryService.java
Labels: Type: Enhancement, Priority: Medium, Duration: Mid, Status: Completed

#295 Lab 6 Pull Request - UI/UX
  3Design/frontend/src/App.tsx
  3Design/frontend/src/components/DViewer/DViewer.tsx
  3Design/frontend/src/components/DiscussionPost/DiscussionPost.tsx
  3Design/frontend/src/components/Feed/Feed.tsx
  3Design/frontend/src/components/GalleryPost/GalleryPost.tsx
  3Design/frontend/src/components/GenericFeed/GenericFeed.tsx
  3Design/frontend/src/components/HomePage/HomePage.tsx
  3Design/frontend/src/components/Login/LoginPage.tsx
  3Design/frontend/src/components/PostPage/PostPage.module.css
  3Design/frontend/src/components/PostPage/PostPage.tsx
  3Design/frontend/src/components/RegisterPage/RegisterPage.tsx
  3Design/frontend/src/components/tsfunctions.ts
  3Design/frontend/src/resources/json-files/MockDiscussions.json
  3Design/frontend/src/resources/json-files/MockGenericPosts.json
  3Design/mobile/app/navigation/TabNavigator.js
  3Design/mobile/app/screens/CategoriesScreen.js
  3Design/mobile/app/screens/CreatePostScreen.js
  3Design/mobile/app/screens/LoginScreen.js
  3Design/mobile/app/screens/RegisterScreen.js
  3Design/mobile/package-lock.json
  3Design/mobile/package.json
Labels: Priority: Critical

#306 Feature/CreatePost
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/controller/GCPTestController.java
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/controller/PostController.java
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/payload/PostCreateRequest.java
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/service/PostService.java
Labels: Type: Enhancement, Duration: Mid

#293 Implement reaction feature fix several comment issues.
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/controller/PostController.java
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/payload/CommentReactionResponse.java
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/payload/ReactionRequest.java
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/payload/ReactionResponse.java
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/repository/ReactionRepository.java
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/service/CommentService.java
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/service/PostService.java
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/service/WikidataService.java
Labels: Priority: High

#320 Implement post retrieval endpoints
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/controller/PostController.java
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/model/enums/Category.java
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/payload/PostResponse.java
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/repository/PostRepository.java
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/service/PostService.java
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/service/WikidataService.java
Labels: Type: Enhancement

#325 Implement user followings.
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/controller/TournamentController.java
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/controller/UserController.java
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/model/Following.java
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/model/TournamentEntry.java
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/repository/FollowingRepository.java
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/repository/TournamentEntryRepository.java
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/service/TournamentService.java
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/service/UserService.java
Labels: Type: Enhancement

#327 Lab 7 Pull Request
  3Design/backend/threedesign/pom.xml
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/controller/AnnotationController.java
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/controller/PostController.java
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/controller/TournamentController.java
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/controller/UserController.java
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/model/Following.java
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/model/TournamentEntry.java
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/model/enums/Category.java
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/payload/AnnotationCreateRequest.java
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/payload/AnnotationResponse.java
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/payload/PostResponse.java
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/repository/CommentRepository.java
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/repository/FollowingRepository.java
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/repository/PostRepository.java
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/repository/TournamentEntryRepository.java
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/service/AnnotationService.java
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/service/CommentService.java
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/service/PostService.java
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/service/TournamentService.java
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/service/UserService.java
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/service/WikidataService.java
  3Design/frontend/src/components/CreatePost/CreatePost.tsx
  3Design/frontend/src/components/HomePage/HomePage.tsx
  3Design/mobile/app/navigation/TabNavigator.js
  3Design/mobile/app/screens/ProfileScreen.js
  3Design/mobile/app/screens/RegisterScreen.js
  3Design/mobile/app/screens/SearchScreen.js
Labels: Type: Enhancement, Type: Maintenance

#336 Implement Category follow unfollow
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/controller/CategoryController.java
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/payload/GetCategoryResponse.java
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/repository/UserCategoryRepository.java
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/service/CategoryService.java
Labels: Type: Enhancement

#339 Frontend Search Results
  3Design/frontend/src/App.tsx
  3Design/frontend/src/components/Comment/Comment.tsx
  3Design/frontend/src/components/DiscussionPost/Clickable/DiscussionPost.tsx
  3Design/frontend/src/components/DiscussionPost/Page/DiscussionPost.tsx
  3Design/frontend/src/components/Feed/Feed.tsx
  3Design/frontend/src/components/GalleryPost/Clickable/GalleryPost.tsx
  3Design/frontend/src/components/GalleryPost/Page/GalleryPost.tsx
  3Design/frontend/src/components/GenericFeed/GenericFeed.tsx
  3Design/frontend/src/components/PageHeader/PageHeader.tsx
  3Design/frontend/src/components/PostPage/PostPage.tsx
  3Design/frontend/src/components/SearchResults/SearchResults.module.css
  3Design/frontend/src/components/SearchResults/SearchResults.tsx
  3Design/frontend/src/components/interfaces.ts
  3Design/frontend/src/components/tsfunctions.ts
  3Design/frontend/src/resources/json-files/Categories.json
  3Design/frontend/src/resources/json-files/Comments.json
  3Design/frontend/src/resources/json-files/MockDiscussions.json
  3Design/frontend/src/resources/json-files/MockGenericPosts.json
  3Design/frontend/src/resources/json-files/MockPosts.json
Labels: Type: Enhancement, help wanted, Priority: High, Duration: Mid

#340 Updated Post Creation Screen
  3Design/mobile/app/navigation/TabNavigator.js
  3Design/mobile/app/screens/CreatePostScreen.js
  3Design/mobile/package-lock.json
  3Design/mobile/package.json
Labels: Type: Enhancement, Priority: High

#345 Frontend - Postmenu Progression
  3Design/frontend/public/default_pp.png
  3Design/frontend/src/components/Annotations/Annotations.module.css
  3Design/frontend/src/components/Annotations/PostAnnotation.tsx
  3Design/frontend/src/components/CreatePost/ChallengePost.tsx
  3Design/frontend/src/components/CreatePost/CreatePost.tsx
  3Design/frontend/src/components/DiscussionPost/Clickable/DiscussionPost.tsx
  3Design/frontend/src/components/DiscussionPost/DiscussionPost.module.css
  3Design/frontend/src/components/DiscussionPost/Page/DiscussionPost.tsx
  3Design/frontend/src/components/Feed/Feed.tsx
  3Design/frontend/src/components/GalleryPost/Clickable/GalleryPost.tsx
  3Design/frontend/src/components/GalleryPost/GalleryPost.module.css
  3Design/frontend/src/components/GalleryPost/Page/GalleryPost.tsx
  3Design/frontend/src/components/Login/LoginPage.tsx
  3Design/frontend/src/components/PageHeader/PageHeader.tsx
  3Design/frontend/src/components/PostPage/PostPage.module.css
  3Design/frontend/src/components/PostPage/PostPage.tsx
  3Design/frontend/src/components/interfaces.ts
  3Design/frontend/src/components/tsfunctions.ts
  3Design/frontend/src/resources/json-files/MockAnnotations.json
Labels: Type: Enhancement, Priority: High, Duration: Short, Status: In Progress

#312 Feature/CreatePost exception handler and join tournement control
  3Design/backend/threedesign/pom.xml
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/controller/PostController.java
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/exception/GlobalExceptionHandler.java
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/payload/PostCreateRequest.java
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/service/PostService.java
Labels: Type: Enhancement, Priority: High

#332 Earn tournament points with interaction
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/repository/CommentRepository.java
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/service/CommentService.java
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/service/PostService.java
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/service/TournamentService.java
Labels: Type: Enhancement

#344 Feature/achievements
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/achievements/BaseAchievement.java
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/achievements/CommenterAchievement.java
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/controller/AchievementController.java
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/model/Achievement.java
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/model/UserAchievement.java
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/model/enums/Achievement.java
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/payload/UserAchievementResponse.java
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/repository/AchievementRepository.java
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/repository/CommentRepository.java
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/repository/PostRepository.java
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/repository/ReactionRepository.java
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/repository/UserAchievementRepository.java
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/service/AchievementService.java
Labels: Type: Enhancement, Priority: High

#346 Add followed users' posts to feed
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/repository/PostRepository.java
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/service/PostService.java
Labels: Type: Enhancement, Status: Review Needed

#348 Implement assignPrize method
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/model/TournamentEntry.java
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/model/enums/Achievement.java
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/repository/TournamentEntryRepository.java
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/service/TournamentService.java
Labels: Type: Enhancement

#360 Frontend - Tournaments
  3Design/frontend/package-lock.json
  3Design/frontend/package.json
  3Design/frontend/src/App.tsx
  3Design/frontend/src/components/Feed/Feed.tsx
  3Design/frontend/src/components/SearchResults/SearchResults.tsx
  3Design/frontend/src/components/TournamentInfo/TournamentInfo.module.css
  3Design/frontend/src/components/TournamentInfo/TournamentInfo.tsx
  3Design/frontend/src/components/TournamentLeaderboard/LeaderboardPage.module.css
  3Design/frontend/src/components/TournamentLeaderboard/LeaderboardPage.tsx
  3Design/frontend/src/components/interfaces.ts
Labels: Type: Enhancement, Priority: Critical, Duration: Mid, Status: In Progress

#376 add swagger implementation
  3Design/backend/threedesign/pom.xml
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/config/OpenApiConfig.java
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/config/SecurityConfiguration.java
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/controller/PostController.java
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/controller/UserController.java
  3Design/backend/threedesign/src/main/java/boun/group8/threedesign/payload/PostCreateRequest.java
Labels: Type: Enhancement

#378 Merge Finalized Version Of Mobile Into main Branch
  3Design/mobile/app.json
  3Design/mobile/app/components/ObjectViewer.js
  3Design/mobile/app/components/Post.js
  3Design/mobile/app/context/CategoryContext.js
  3Design/mobile/app/navigation/StackNavigator.js
  3Design/mobile/app/navigation/TabNavigator.js
  3Design/mobile/app/screens/CategoriesScreen.js
  3Design/mobile/app/screens/CreatePostScreen.js
  3Design/mobile/app/screens/FeedScreen.js
  3Design/mobile/app/screens/LeaderboardScreen.js
  3Design/mobile/app/screens/LoginScreen.js
  3Design/mobile/app/screens/PostScreen.js
  3Design/mobile/app/screens/ProfileScreen.js
  3Design/mobile/package-lock.json
  3Design/mobile/package.json
Labels: Priority: High

#386 Comment Service Unit Tests
  3Design/backend/threedesign/src/test/java/boun/group8/threedesign/service/CommentServiceTest.java
  3Design/backend/threedesign/src/test/java/boun/group8/threedesign/service/FileServiceTest.java
  3Design/backend/threedesign/src/test/java/boun/group8/threedesign/util/TestDataBuilder.java
Labels: Documentation, Duration: Short

#387 Umit Test for file service
  3Design/backend/threedesign/src/test/java/boun/group8/threedesign/service/FileServiceTest.java
Labels: Documentation, Duration: Short
